server:
  port: 5003
  host: localhost
auth:
  jwksUri: http://localhost:5001/.well-known/jwks.json
database:
  url: mongodb+srv://raj2704:xLPcOOHbG1mhRMLD@pizzaapp.4v6bymu.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster0&ssl=true
kafka:
  brokers: [localhost:9092]
  order_topic: order
  sasl:
    username: ""
    password: ""
razorpay:
  key_id: rzp_test_RrDEUdK08o2JAr
  key_secret: PNUZXlyseaTwyPLqSg0uNL3o
client:
  url: http://localhost:3000
frontend:
  clientUI: http://localhost:3000
  adminUI: http://localhost:5173
  apiGateway: http://localhost:8000
